### ISSUE TITLE
It won't work for python v2.7.5 and prior

### ISSUE THREAD

**Issue by jliang888** [toddrob99/Webhooks#3]
Traceback (most recent call last):
  File "./webhooklisterner.py", line 79, in <module>
    webhooks.start()
  File "/usr/lib/python2.7/site-packages/webhook_listener/__init__.py", line 31, in start
    self.WEBTHREAD = threading.Thread(target=self._startServer, name='webhooks_websever', daemon=True)
TypeError: __init__() got an unexpected keyword argument 'daemon'

Please split line 31
self.WEBTHREAD = threading.Thread(target=self._startServer, name='webhooks_websever', daemon=True)
To
self.WEBTHREAD = threading.Thread(target=self._startServer, name='webhooks_websever') self.WEBTHREAD.daemon = True
Will work for all, since last arg daemon=True isn't added to the function until 2.7.6

Thanks.

**Comment by toddrob99** [comment]
Python 2 is not supported, but this is a simple enough change that I don't mind doing it.

**Comment by toddrob99** [comment]
Merged and update pushed to PyPI (v0.0.3). Please use python 3 whenever possible. Thank you for using my module.
