### ISSUE TITLE
Might not be an issue but possible.

### ISSUE THREAD

**Issue by jliang888** [toddrob99/Webhooks#5]
I am not 100% sure this will be an issue, I hope python3 doesn't have such a warning.

When you ctrl+c to stop the webhook listener, you will get the following warning:

/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py:258: RuntimeWarning: The main thread is exiting, but the Bus is in the states.STOPPED state; shutting it down automatically now. You must either call bus.block() after start(), or call bus.exit() before the main thread exits.

Thanks.

**Comment by toddrob99** [comment]
I've been ignoring this warning because the bus exits automatically anyway. I'll eventually shut down the bus explicitly. Thanks for opening the issue so I'll remember to do it.

**Comment by buanzo** [comment]
Hi, I am using your module to implement a webhook server to integrate https://github.com/buanzo/hume/ with Prometheus' AlertManager. I got here wanting to open this issue, but I found it already opened :)

So I am sending you a PR just to fix it.

**Comment by toddrob99** [comment]
Fixed in v1.0.0 - `pip install --upgrade webhook_listener`
